### ISSUE TITLE
Ubuntu / Package wget is not available. simcado.get_extras() will not work.

### ISSUE THREAD

**Issue by michaelmach** [astronomyk/SimCADO#22]
It seems that (at least on my machine) the module 'wget' (not 'python-wget') needs to be in the dependecies altogether. Neither the standard installation of python that comes with ubuntu, nor anaconda seem to include this package by default.

**Comment by michaelmach** [comment]
Dependencies are listed in the SimCADocs

http://www.univie.ac.at/simcado/Download.html

**Comment by oczoske** [comment]
Line describing pip installation has been added to Download.rst
