### ISSUE TITLE
optics.get_filter_curve prints "file not found" even if it finds it. 

### ISSUE THREAD

**Issue by miguelverdugo** [astronomyk/SimCADO#37]
e.g. sim.optics.get_filter_curve("Ks")

The issue is caused by 
line 705>  fname = find_file(filter_name) 
that prints that error, even if later get_filter_curve is able to find the file or raise an error if not. 

it is possible to silence the message with contextlib but I'm unsure whether it's the proper solution.

**Comment by oczoske** [comment]
I would advocate using full file names (in this case `TC_filter_Ks.dat`) as required by `find_file()`. If we decide to continue supporting abbreviations, they should be resolved before calling `find_file()`. This would work if there is exactly one file per filter name within the instrument package that is used.

**Comment by oczoske** [comment]
I misunderstood the original issue: `find_file()` prints a message when it does not find a file. This is superfluous and confusing in this case. It is now silenced by adding `silent=True` in the call within `get_filter_curve()`.

**Comment by astroleo** [comment]
Although it's not related to the OP's issue, I would like to support using full file names. Hardly more effort to type and it is good to be as explicit as possible to avoid confusion.
