### ISSUE TITLE
How to install SimCADO?

### ISSUE THREAD

**Issue by hugobuddel** [astronomyk/SimCADO#48]
So many things have changed (for the better) in the last couple of months that I'm not sure how to install SimCADO anymore.

## From Binary
The readme.md instructions are essentially
```
pip install http://www.univie.ac.at/simcado/SimCADO.tar.gz
python -c "import simcado; simcado.get_extras()"
```
This will install SimCADO 0.4.dev0 with incompatible extras:
```
python -c "import simcado; simcado.run(simcado.source.source_1E4_Msun_cluster())"
Traceback (most recent call last):
[..]
  File "[..]/simcado/optics.py", line 381, in _gen_all_tc
    self.cmds["SCOPE_TEMP"] = mirr_list["Temp"][0]
  File "[..]/simcado/commands.py", line 706, in __setitem__
    raise ValueError(key+" not in UserCommands.keys()")
ValueError: SCOPE_TEMP not in UserCommands.keys()
```

## From Source
```
git clone https://github.com/astronomyk/SimCADO.git
cd SimCADO
python setup.py install
```
This will only copy the `data` directory into the site-packages of Python, so there is no Python code:
```
python -c "import simcado; simcado.run(simcado.source.source_1E4_Msun_cluster())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'simcado' has no attribute 'run'
```

## Manually Copying Source
```
git clone https://github.com/astronomyk/SimCADO.git
cp -a SimCADO/simcado [..]/python3.7/site-packages/
```
results in
```
python -c "import simcado; simcado.run(simcado.source.source_1E4_Msun_cluster())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[..]/simcado/source.py", line 2092, in source_1E4_Msun_cluster
    weight=weight, units="ph/s/m2")
  File "[..]/simcado/source.py", line 251, in __init__
    self._from_arrays(lam, spectra, x, y, ref, weight)
  File "[..]/simcado/source.py", line 1046, in _from_arrays
    if len(spectra.shape) == 1:
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by astronomyk** [comment]
Hi Hugo,

firstly thanks for taking the time to play with simcado and for also letting us know where everything is failing. Unfortunately you're timing here isn't the greatest. I'm in the middle of doing a big code refactor to sort out the structure of the whole package to make it more flexible. The goal is to have this finished by the consortium meeting in a month. 
Hence I don't suggest using the source code as a base for installing simcado.

The Binary should work fine except for the main config file which seems to be out of date. @miguelverdugo is currently working on updating this. Essentially all you need to do to get the binary working is add the line

    SCOPE_TEMP  0  

to the default.config file which will be in the simcado/data directory. This can be found with 

    simcado.__data_dir__

If that doesn't work, let me know.

**Comment by hugobuddel** [comment]
Thank you @astronomyk and @miguelverdugo, it works. Using the prepackaged version is fine for now.

I'm trying to see whether we can integrate SimCADO with our prototype pipeline, so we can create simulated data directly. (E.g. just use the `HDUList` that `simcado.run()` provides directly.) Everything will probably change once you got the refactoring done and that's fine.

This is what I've added to our [continuous integration](https://gitlab.astro-wise.org/micado/micadowise/blob/8-integrate-simcado/.gitlab-ci.yml) now:

```bash
conda install astropy scipy
pip install poppy wget
pip install http://www.univie.ac.at/simcado/SimCADO.tar.gz
python -c "import simcado; simcado.get_extras()"
echo "SCOPE_TEMP  0" >> "$(python -c 'import site; print(site.getsitepackages()[0])')/simcado/data/default.config"
```

The demo from the readme.md is added as a test, so it will be ran with every pushed commit. I'll let you know when something breaks :smile_cat:.

**Comment by astronomyk** [comment]
Great thanks!

**Comment by miguelverdugo** [comment]
Hi Hugo
As Kieran said, adding the keyword SCOPE_TEMP to the config file solves the problem. Anyway, I also added it to the default.config file so nobody else experiences the same issue. That is, the default.config file you get with get_extras() has that keyword included.  The issue arises because in v0.5 the keyword was renamed to SCOPE_TEMPERATURE. 

I'm currently busy with improving the documentation as well as in code examination so we will have v0.5 as an interim version until the new (refractored) version is available. If you want yo try the v0.5 (which contains some improvements), the best solution for now is just to copy the *.py files to your simcado.__pkg_dir__ . I will look on the issue how to install it from the repository. It was working before...

If you encounter other issues please let us know

**Comment by hugobuddel** [comment]
Thank you @miguelverdugo, the packaged version works properly again.

Perhaps it would be possible to add some versioning to `get_extras()`? As in, that it will only fetch files that are appropriate to the version of SimCADO. But maybe that is a bit overkill for now.

**Comment by hugobuddel** [comment]
pip install works nicely, closing

/close

**Comment by mfouesneau** [comment]
Data does not install with pip.
fresh installation python3.9

**Comment by hugobuddel** [comment]
@mfouesneau , all development has moved to [ScopeSim](https://github.com/AstarVienna/ScopeSim) is it possible for you to use that instead of SimCADO?
