### ISSUE TITLE
Throws an error when simulating full detector array with no sources outer fields

### ISSUE THREAD

**Issue by astronomyk** [astronomyk/SimCADO#68]
Why?
Try to reproduce

**Comment by gbcaminha** [comment]
lam, spec = simcado.source.SED("starburst", filter_name="Ks", magnitude=20)

    im_sersic = simcado.source.sersic_profile(r_eff = 100, width=10024, \
                                              height=10024, \
                                             x_offset=200, y_offset=200)

    im_spiral_2 = simcado.source.spiral_profile(r_eff = 100, width=1024, \
                                             x_offset=0, y_offset=0)




    lam = lam

    my_src = simcado.source.source_from_image(images=im_sersic, lam=lam, spectra=spec, plate_scale=0.004)


    my_run_cmds = simcado.UserCommands()

    my_run_cmds["OBS_EXPTIME"] = 3600
    my_run_cmds["OBS_NDIT"] = 1
    my_run_cmds["FPA_CHIP_LAYOUT"] = "full"


    simcado.run(my_src, filename="my_image.fits", cmds=my_run_cmds)

**Comment by miguelverdugo** [comment]
I can reproduce it.  
I guess that an empty array is being passed to scipy.ndimage.sum but I'd time to dig out the problem

As a workaround I'd suggest to set sub_pixel=True in simcado.run until we can debug it

**Comment by oczoske** [comment]
The example code is running without throwing an error now. I close the issue.
